# syntax=docker/dockerfile:1

FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_NODE_ENV
ARG VITE_BACKEND_URL_LOCAL
ARG VITE_BACKEND_URL_SERVER
ARG VITE_FRONTEND_URL_LOCAL
ARG VITE_FRONTEND_URL_SERVER

ENV VITE_NODE_ENV=${VITE_NODE_ENV}
ENV VITE_BACKEND_URL_LOCAL=${VITE_BACKEND_URL_LOCAL}
ENV VITE_BACKEND_URL_SERVER=${VITE_BACKEND_URL_SERVER}
ENV VITE_FRONTEND_URL_LOCAL=${VITE_FRONTEND_URL_LOCAL}
ENV VITE_FRONTEND_URL_SERVER=${VITE_FRONTEND_URL_SERVER}

RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
