version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_NODE_ENV: production
        VITE_BACKEND_URL_LOCAL: http://localhost:3000
        VITE_BACKEND_URL_SERVER: ${VITE_BACKEND_URL_SERVER}
        VITE_FRONTEND_URL_LOCAL: http://localhost:5050
        VITE_FRONTEND_URL_SERVER: ${VITE_FRONTEND_URL_SERVER}
    ports:
      - "5050:80"
    restart: unless-stopped
