name: Deploy Frontend Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create .env file from GitHub Secrets
        run: |
          echo "${{ secrets.FRONTEND_ENV }}" > .env

      - name: Install and Build
        run: |
          npm install
          npm run build
          zip -r deploy.zip dist

      - name: Copy zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deploy.zip"
          target: "/root/Komol/front/FRONT-8-MONTH"

      - name: Finalize Deployment on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export PM2_HOME=/root/.pm2
            cd /root/Komol/front/FRONT-8-MONTH
            
            git checkout staging
            git pull origin staging
            
            rm -rf dist
            unzip -o deploy.zip
            
            pm2 restart frontend-staging --update-env || pm2 serve dist 5050 --name "frontend-staging" --spa
            
            pm2 save
            rm -f deploy.zip
            echo "✅ Frontend GitHub Secrets orqali build bo'ldi va yangilandi!"